services:
  # Backend service
  - type: web
    name: securefile-backend
    runtime: docker
    buildCommand: docker build -t backend ./backend
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: securefile-db
          property: connectionString

  # Frontend service
  - type: web
    name: securefile-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL_PROD
        value: https://fortifile-backend.onrender.com/api/v1

databases:
  - name: securefile-db
    ipAllowList: []