services:
  backend:
    build: 
      context: ${LOCAL_WORKSPACE_FOLDER}/backend  # This ensures the correct path resolution
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - backend-node-modules:/app/node_modules
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONDONTWRITEBYTECODE=1

volumes:
  backend-node-modules: