# Generated by Django 5.1.4 on 2024-12-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, help_text='Secret key for TOTP-based multi-factor authentication', max_length=32, null=True),
        ),
    ]
