# Generated by Django 5.1.4 on 2024-12-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='client_key',
            field=models.CharField(blank=True, help_text='Client-side encryption key', max_length=512, null=True),
        ),
    ]
