# Generated by Django 5.1.4 on 2024-12-20 18:18

import django.db.models.deletion
import files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_client_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='expires_at',
            field=models.DateTimeField(default=files.models.get_default_expiry),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='permission',
            field=models.CharField(choices=[('VIEW', 'View Only'), ('DOWNLOAD', 'View and Download')], default='VIEW', max_length=10),
        ),
    ]
