# Generated by Django 5.1.4 on 2024-12-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_id_alter_file_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='shared_with_email',
            field=models.EmailField(help_text='Email address this file was shared with', max_length=254, null=True),
        ),
    ]
